embedder:
  provider: OPENAI
  model: text-embedding-3-small

rag:
  provider: qdrant # qdrant | chroma_db

qdrant:
  retrieval_mode: hybrid # dense | sparse | hybrid
  collection_name: codebase
  batch_size: 50

chroma_db:
  persist_directory: .chromadb/
  collection_name: codebase

elasticsearch:
  url: http://localhost:9200
  index_name: codebase

llm:
  provider: OPENAI
  model: gpt-4o
  temperature: 0.2

agent:
  max_tool_calls: 3
  max_model_calls: 5

# memory layer
memory:
  persist_directory: .memory/memory.db
  summarize_threshold: 3
  keep_last_messages: 2