embedder:
  provider: OPENAI
  model: text-embedding-3-small

rag:
  provider: qdrant # qdrant | chroma_db

qdrant:
  retrieval_mode: hybrid # dense | sparse | hybrid
  collection_name: codebase
  batch_size: 50

chroma_db:
  persist_directory: .chromadb/
  collection_name: codebase

elasticsearch:
  url: http://localhost:9200
  index_name: codebase

llm:
  provider: OPENAI
  model: gpt-4o
  temperature: 0.2

agent:
  max_tool_calls: 5
  max_model_calls: 5

# memory layer
memory:
  persist_directory: .memory/memory.db
  summarize_threshold: 1000
  keep_last_messages: 3

mcp:
  github:
    selected_tools:
      [
        "create_or_update_file",
        "get_file_contents",
        "search_repositories",
        "create_repository",
        "push_files",
        "create_branch", 
        "list_commits"
      ]

  filesystem:
    selected_tools:
      [
        "read_text_file",
        "read_media_file",
        "read_multiple_files",
        "write_file",
        "edit_file",
        "list_files",
        "create_directory",
        "move_file",
        "get_file_info"
      ]
    
  gmailserver:
    selected_tools:
      [
        "send_email",
        "read_email",
        "search_emails",
        "list_emails"
      ]
